name: Use polkadot and staking-miner-playground binaries
description: Downloads and configures the polkadot binary built with build-polkadot
runs:
  using: composite
  steps:
    - name: Download polkadot binaries
      id: download-artifact
      uses: dawidd6/action-download-artifact@268677152d06ba59fcec7a7f0b5d961b6ccd7e1e # v2.28.0
      with:
        workflow: build-polkadot.yml
        name: nightly-polkadot-binary

    - name: Download staking-miner-playground binary
      id: download-artifact
      uses: dawidd6/action-download-artifact@268677152d06ba59fcec7a7f0b5d961b6ccd7e1e # v2.28.0
      with:
        workflow: build-staking-miner-playground.yml
        name: staking-miner-playground-binary

    - name: Debug
      run: |
        ls -la
        # ls -la ~/.local/bin

    - name: Prepare polkadot-node binary
      shell: bash
      run: |
        chmod u+x ./polkadot*
        ./polkadot --version
        mkdir -p ~/.local/bin
        cp ./polkadot* ~/.local/bin
