name: Build polkadot binary

on:
  # Allow it to be manually ran to rebuild binary when needed:
  workflow_dispatch: {}
  # Run at 22pm every week on Sunday's for nightly builds.
  # schedule:
  #   - cron: "0 0 * * *"

jobs:
  tests:
    name: Build polkadot binary
    runs-on: ubuntu-latest
    container: paritytech/ci-unified:bullseye-1.74.0-2023-11-01-v20231204
    steps:
      - name: checkout polkadot-sdk
        uses: actions/checkout@v4
        with:
          repository: paritytech/polkadot-sdk

      # - name: Install dependencies
      #   run: sudo apt-get install -y protobuf-compiler

      # - name: Install WASM toolchain
      #   run: rustup target add wasm32-unknown-unknown

      # - name: Install WASM toolchain
      #   run: rustup component add rust-src

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            polkadot
          cache-on-failure: true

      - name: build polkadot binary
        run: |
          cargo build -p polkadot --release --features fast-runtime
          ls -l
          ls -l ./target/release/polkadot
          polkadot --version

      - name: upload polkadot binary
        uses: actions/upload-artifact@v3
        with:
          name: polkadot-nightly
          path: ./target/release/polkadot
          retention-days: 2
          if-no-files-found: error